%% Exports data of the FOB microscope for LaTeX

parameters = struct( ...
    'path', '.', ...
    'filename', 'Brillouin-2', ...
    'ODT', struct( ...
        'RI', struct( ...
            'cax', [1.337 1.47] ...
        ) ...
    ), ...
    'BM', struct( ...
        'validity', 40, ...
        'shift', struct( ...
            'cax', [7.3 9.0] ...
        ), ...
        'intensity', struct( ...
            'cax', [0 1] ...
        ) ...
   ), ...
   'Modulus', struct( ...
        'validity', 40, ...
        'M', struct( ...
            'cax', [2 4.4] ...
        ), ...
        'M_woRI_norm', struct( ...
            'cax', [-60 60] ...
        ) ...
    ), ...
   'Fluorescence', struct( ...
        'backgroundFile', 'background_Brillouin-2', ...
        'combinations', {{'rg_', 'rgb'}} ...
    ) ...
);

%% directory for the plots
plotDir = [parameters.path filesep 'Plots'];
if ~exist(plotDir, 'dir')
    mkdir(plotDir);
end
barePlotDir = [plotDir filesep 'Bare'];
if ~exist(barePlotDir, 'dir')
    mkdir(barePlotDir);
end
axisPlotDir = [plotDir filesep 'WithAxis'];
if ~exist(axisPlotDir, 'dir')
    mkdir(axisPlotDir);
end

%% Refractive index
plotRefractiveIndex(parameters);

%% Fluorescence and Brightfield
plotFluorescence(parameters);
plotCombinedFluorescence(parameters);

%% Brillouin shift and longitudinal modulus
plotBrillouinModulus(parameters);
plotBrillouinModulusDeviation(parameters);

